Team2021/urls.py
from django.contrib import admin
from django.conf.urls import include
from django.urls import path

urlpatterns = [
    path('', include('login.urls')),
    path('admin/', admin.site.urls),
    path('create/', include('createRingisyo.urls')),
    path('account/', include('createAccount.urls')),
    path('dep/', include('createDep.urls')),
    path('position/', include('position.urls')),
    path('login/', include('login.urls')),
    path('list/', include('ringiList.urls')),
    path('top/', include('topPage.urls')),
    path('common/', include('common.urls')),
]

createDep/urls.py
from django.urls import path
from createDep import views

app_name = 'dep'

urlpatterns = [
    path('create/', views.create, name='create'),
    path('dep-list/', views.dep_list, name='dep-list'),
    path('position-list/<int:num>/', views.position_list, name='position-list'),
    path('director/<int:num>/', views.director, name='director'),
    path('chief/<int:num>/', views.chief, name='chief'),
    path('employee-1/<int:num>/', views.employee_1, name='employee-1'),
    path('employee-2/<int:num>/', views.employee_2, name='employee-2'),
    path('user-list/<int:num>/', views.user_list, name='user-list'),
    path('', views.top, name='top')
    #     position-list,
]

login/urls.py
from django.urls import path
from login import views

app_name = 'login'

urlpatterns = [
    # .../account/にアクセスがあった時、views.pyのindex関数を呼び出す
    path('', views.login, name='login'),
    path('first/', views.first, name='first'),
    path('logout/', views.logout, name='logout')
]

sample/urls.py
from django.urls import path
from sample import views

app_name = 'sample'

urlpatterns = [
    path('', views.index, name='sample_index'),
]

createDep/views.py
from django.db.models import Q
from django.shortcuts import render, redirect
from common.models import *
from Team2021 import slack_message as s_m_send


# Create your views here.
# 表示される一覧は登録済みのデータのみ
# 社員選択画面の一覧に、
# 部長 : 部長と一般社員
# 主任 : 主任と一般社員
# 一般社員 : 一般社員のみ
# を表示する
# 社員選択画面から戻る時、データを登録する
# 解除ボタンを押したとき、処理を実行する


def create(request):
    context = {'alert': 'no_checked'}
    if request.method == 'POST':
        if 'select' in request.POST:  # 「所属社員」ボタンを押したとき
            if 'dep_name' in request.POST:
                request.session['dep_name'] = request.POST['dep_name']
            user_array = User.objects.select_related().filter(position_id=6)
            context['user_array'] = user_array
            return render(request, 'createDep/selectUser.html', context)
        elif 'back' in request.POST:  # 「戻る」ボタンを押したとき
            if 'dep_name' in request.session:
                del request.session['dep_name']
            return render(request, 'createDep/sample.html', context)
        elif 'create' in request.POST:  # 「作成」ボタンを押したとき
            if 'dep_name' not in request.POST or request.POST['dep_name'] == '':
                context['alert'] = 'no_name'
                return render(request, 'createDep/newDep.html', context)
            else:
                if 'dep_name' in request.session and 'dep_name' in request.POST:
                    del request.session['dep_name']
                    # TODO: createのDB登録、更新
                    #   要)部署名、社員ID  ( request.POST['dep_name'], session['new_user_list'] )
                    #   Department_name -> request.POST['dep_name'],
                    #   session['new_user_list'].dep_id -> num,
                    #   session['new_user_list'].boss_id -> null,
                    new_dep = Department(department_name=request.POST['dep_name'])
                    new_dep.save()
                    if 'new_user_list' in request.session:
                        data = Department.objects.order_by("department_id").last()
                        up_former = User.objects.filter(user_id__in=request.session['new_user_list']).update(
                            department=data)

                    mail_message = [{'email': User.objects.get(pk='00000001').mail + '@morijyobi.ac.jp',
                                     'message': new_dep.department_name + '部を作成しました。'}]

                    s_m_send.send_message_for_email(mail_message)

                    return render(request, 'createDep/sample.html', context)
                elif 'dep_name' not in request.POST:
                    del request.session['del_name']
                    context['alert'] = 'no_name'
                    return render(request, 'createDep/newDep.html', context)
                elif 'dep_name' in request.POST:
                    #   同上
                    new_dep = Department(department_name=request.POST['dep_name'])
                    new_dep.save()
                    if 'new_user_list' in request.session:
                        data = Department.objects.order_by("department_id").last()
                        up_former = User.objects.filter(user_id__in=request.session['new_user_list']).update(
                            department=data)
                    mail_message = [{'email': User.objects.get(pk='00000001').mail + '@morijyobi.ac.jp',
                                     'message': new_dep.department_name + '部を作成しました。'}]

                    s_m_send.send_message_for_email(mail_message)

                    return render(request, 'createDep/sample.html', context)
    elif request.method == 'GET':
        if 'cb' in request.GET:
            lists = request.GET.getlist('cb')
            if lists[0] == '00000000' and len(lists) == 1:
                if 'new_user_list' in request.session:
                    del request.session['new_user_list']
                context['alert'] = 'no_checked'
            else:
                context.pop('alert', None)
                request.session['new_user_list'] = lists  # 部署登録時に一般社員で登録する社員id一覧
                print(User.objects.filter(user_id__in=request.session['new_user_list']))
            # checkboxを選択せずに決定ボタンを押すと、このifで弾かれる模様
        if 'dep_name' in request.session:
            context['dep_name'] = request.session['dep_name']
            return render(request, 'createDep/newDep.html', context)
        return render(request, 'createDep/newDep.html', context)


def dep_list(request):
    if 'dep_name' in request.session:
        del request.session['dep_name']
    dep_and_user = User.objects.filter(position_id=4, department_id__gt=2)
    dep_info = Department.objects.filter(department_id__gt=2)
    # for array in dep_info:
    #     print(array.dep_foreign_id.filter(position_id=4))
    context = {'department': dep_info}
    # deps = []
    # for array in dep_and_user:
    #     deps.append(array.department_id)
    # if len(deps) != len(set(deps)):
    #     print("部長の重複を確認")
    return render(request, 'createDep/depList.html', context)


def position_list(request, num):
    if request.method == 'POST':
        if 'director' in request.POST:
            return redirect('dep:director', request.session['dep_id'])
        if 'chief' in request.POST:
            return redirect('dep:chief', request.session['dep_id'])
        if 'employee' in request.POST:
            return redirect('dep:employee-1', request.session['dep_id'])
        if 'back' in request.POST:
            return redirect('dep:dep-list')
    elif request.method == 'GET':
        dr = User.objects.filter(position_id=4, department_id=num).values('last_name', 'first_name')
        chf = User.objects.filter(position_id=5, department_id=num).count()
        emp = User.objects.filter(position_id=6, department_id=num).count()
        if dr.first() is None:
            context = {
                'num': num,
                'dr': dr,
                'chf': chf,
                'emp': emp
            }
        else:
            context = {
                'num': num,
                'dr': dr[0],
                'chf': chf,
                'emp': emp
            }
        request.session['dep_id'] = num
        return render(request, 'createDep/positionList.html', context)


def director(request, num):
    context = {}
    if request.method == 'POST':
        if 'edit' in request.POST:
            user_array = User.objects.select_related().filter(
                Q(position_id=6) | Q(position_id=4), Q(department_id=num) | Q(department_id=2))
            user_checked = User.objects.filter(position_id=4, department_id=num).values_list('user_id', flat=True)
            context = {'user_array': user_array, 'flg': 'dr', 'num': num, 'checked': user_checked}
            return render(request, 'createDep/selectUser.html', context)
        elif 'back' in request.POST:
            return redirect('dep:position-list', num)
        elif 'decision' in request.POST:
            # TODO: directorのDB登録、更新
            #   要) 前部長ID, 次部長ID, 所属部署 ( User.user_id(position_id, department_id), User.user_id(session['next_dir_id']) ), num
            #   boss_id : 前部長 -> 次部長 , department_id -> num, position_id -> 4,
            #   前部長をboss_idに持つユーザのboss_id -> session['next_dir_id']
            #   前部長のpos_id -> 6,
            #   次部長のpos_id -> 4,
            #   次部長のdep_id -> num,
            boss_before = User.objects.get(position_id=4, department_id=num)
            # print(boss_id_ahead[0]['user_id'])  # 前部長id
            # print(request.session['next_dir_id'])  # 次部長id
            # print(num)
            dep = Department.objects.get(pk=num)
            pos_4 = Position.objects.get(pk=4)
            pos_6 = Position.objects.get(pk=6)
            boss_ahead = User.objects.get(pk=request.session['next_dir_id'])
            # 現在の部署の部長を取得できない(存在しない)場合
            if boss_before is None:  # 現在の部長を取得できなかった時
                chief_list = User.objects.filter(position_id=5, department_id=num)
                # 現在の部署の部長を取得できた(存在する)場合
                if chief_list.first() is not None:
                    # 上司がいないアカウントを指定するとindexError indexoutofrange が発生する
                    chief_list.update(boss=boss_ahead)
                boss_ahead.position = pos_4
                boss_ahead.department = dep
                boss_ahead.save()
            else:  # 現在の部長が存在した時
                # pos4, 6
                # print(User.objects.filter(boss_id=boss_id_ahead[0]['user_id']))

                User.objects.filter(boss_id=boss_before.user_id).update(boss=boss_ahead)

                boss_before.position = pos_6
                boss_before.save()
                boss_ahead.position = pos_4
                boss_ahead.department = dep
                boss_ahead.save()
            mail_message = [{'email': User.objects.get(pk='00000001').mail + '@morijyobi.ac.jp',
                             'message': dep.department_name + '所属の部長を編集しました'}]

            s_m_send.send_message_for_email(mail_message)

            return redirect('dep:position-list', num)
    elif request.method == 'GET':
        if 'cb' in request.GET:
            # 社員選択画面からの遷移
            lists = request.GET.getlist('cb')
            user_data = User.objects.filter(user_id__in=lists)
            if lists[0] == '00000000' and len(lists) == 1:
                context = {'dr': user_data, 'dep_id': num, 'alert': 'no_checked'}
            elif len(lists) >= 3:
                context = {'dr': user_data, 'dep_id': num, 'alert': 'duplicate_director'}
            else:
                request.session['next_dir_id'] = user_data[0].user_id
                context = {'dr': user_data[0], 'dep_id': num}
            return render(request, 'createDep/change1.html', context)
        dr = User.objects.filter(position_id=4, department_id=num)
        if dr.first() is None:
            context = {'dr': dr, 'dep_id': num}
        else:
            context = {'dr': dr[0], 'dep_id': num}
        return render(request, 'createDep/change1.html', context)


def chief(request, num):
    context = {}

createDep/templates/createDep/change1.html
{% extends 'createDep/base.html' %}
{% load static %}
<html lang="ja">

{% block title %}
    部署作成
{% endblock %}

<head>
    {% block addCSS %}
        <link rel="stylesheet" href="{% static 'createDep/css/change1.css' %}">
    {% endblock %}

    <title>list</title>
    <meta charset="UTF-8">
    <!-- <link rel="stylesheet" href="../../static/createDep/css/bootstrap.min.css">
    <link rel="stylesheet" href="../../static/createDep/css/bootstrap.min.css.map">
    <link rel="stylesheet" href="../../static/createDep/css/change1.css"> -->
</head>

<body>
{% block body %}
    <div class="overflow">
        <form action="{% url 'dep:director' dep_id %}" method="POST">
            {% csrf_token %}
            <div class="d-grid gap-2">
                <h1>部長</h1>
                <div class="d-flex justify-content-start">
                    <div class="id">ID : <span>{{ dr.user_id }}</span></div>
                    <div class="name">
                        {% if dr.last_name and dr.first_name %}{{ dr.last_name }}{{ dr.first_name }}{% else %}
                            選択されていません{% endif %}</div>
                </div>
                <button class="btn btn-secondary" name="edit">編集</button>
                <div class="group_btn d-flex justify-content-end">
                    <button class="btn btn-primary back_btn" name="back">戻る</button>
                    <button class="btn btn-primary create_btn" name="decision" id="edit">決定</button>
                </div>
            </div>
        </form>
    </div>
{% endblock %}

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
<script src="../../static/createDep/js/bootstrap.min.js"></script>
<script src="../../static/createDep/js/bootstrap.min.js.map"></script>
{% block addJS %}
    {% if alert %}
        <script>
            {% if 'no_checked' in alert %}
                window.alert('部長が一人も選択されていません。');
            {% elif 'duplicate_director' in alert %}
                window.alert('部長が二人以上選択されています。');
            {% endif %}
            $(function () {
                $("#edit").on('click', function (e) {
                    window.alert('部長が選択されていません。\n部長を選択してください。');
                    e.preventDefault();
                })
            })
        </script>
    {% endif %}
{% endblock %}
</body>
</html>

createDep/templates/createDep/change3.html
{% extends 'createDep/base.html' %}
{% load static %}
<html lang="ja">

{% block title %}
    一般社員1
{% endblock %}

<head>
    {% block addCSS %}
        <link rel="stylesheet" href="{% static 'createDep/css/change3.css' %}">
    {% endblock %}

    <title>list</title>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="../../static/createDep/css/bootstrap.min.css">
    <link rel="stylesheet" href="../../static/createDep/css/bootstrap.min.css.map">
    <link rel="stylesheet" href="../../static/createDep/css/change3.css">
</head>

<body>
{% block body %}
    <div class="overflow">

        <div class="d-grid gap-2">
            <h1>主任を選択してください</h1>
            {% for array in emp %}
                <button class="d-flex justify-content-start"
                        onclick="location.href=&quot;{% url 'dep:employee-2' array.user_id %}&quot;">
                    <div class="id">ID : <span>{{ array.user_id }}</span></div>
                    <div class="name">{{ array.last_name }}{{ array.first_name }}</div>
                </button>
            {% endfor %}
            <form action="{% url 'dep:employee-1' dep_id %}" method="POST">{% csrf_token %}
                <div class="group_btn d-flex justify-content-end">
                    <button class="btn btn-primary back_btn" name="back">戻る</button>
                    <button class="btn btn-primary create_btn" name="decision">決定</button>
                </div>
            </form>
        </div>
    </div>
{% endblock %}

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
<script src="../../static/createDep/js/bootstrap.min.js"></script>
<script src="../../static/createDep/js/bootstrap.min.js.map"></script>
</body>
</html>

createDep/templates/createDep/change4.html
{% extends 'createDep/base.html' %} {% load static %}
<html lang="ja">

{% block title %} 一般社員2 {% endblock %}

<head>
    {% block addCSS %}
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.3/css/all.css" integrity="sha384-SZXxX4whJ79/gErwcOYf+zWLeJdY/qpuqC4cAa9rOGUstPomtqpuNWT9wdPEn2fk" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'createDep/css/change4.css' %}"> {% endblock %}

    <title>list</title>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="../../static/createDep/css/bootstrap.min.css">
    <link rel="stylesheet" href="../../static/createDep/css/bootstrap.min.css.map">
    <link rel="stylesheet" href="../../static/createDep/css/change4.css">
</head>

<body>
    {% block body %}
    <div class="overflow">
        <form action="{% url 'dep:employee-2' boss_id %}" method="POST">{% csrf_token %}
            <div class="d-grid gap-2">
                <div class="title_name">有原 隆乃介</div>
                <button class="btn btn-secondary" name="edit">追加</button>
                <table class="table table-bordered">
                    <thead>
                        <tr class="th_row">
                            <th class="th_id th">社員ID</th>
                            <th class="th_name th">名前</th>
                            <th class="th_lift th">解除</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for array in user_data %}
                        <tr class="tr_main">
                            <td class="td_id"><input type="checkbox" class="check-emp" checked name="u-cb" value="{{ array.user_id }}">{{ array.user_id }}</td>
                            <td class="td_name">{{ array.last_name }}{{ array.first_name }}</td>
                            <td class="td_lift"><i class="fas fa-lock-open icon_disabled"></i><i class="fas fa-lock"></i>
                            </td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
                <div class="btn_div">
                    <button class="btn btn-secondary" name="back" id="back">戻る</button>
                    <button class="btn btn-secondary" name="decision" id="edit">決定</button>
                </div>
            </div>
        </form>
    </div>
    {% endblock %}

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <script src="../../static/createDep/js/bootstrap.min.js"></script>
    <script src="../../static/createDep/js/bootstrap.min.js.map"></script>
    <script src="../../static/createDep/js/change4.js"></script>
    {% block addJS %}
    <script src="{% static 'createDep/js/change4.js' %}"></script>
    {% if alert %}
    <script>
        { %
            if 'no_checked' in alert %
        }
        window.alert('一般社員が一人も選択されていません。'); { % elif 'duplicate_director' %
        }
        window.alert('部長が二人以上選択されています。'); { % endif %
        }
        $(function() {
            $("#edit").on('click', function(e) {
                let bool = window.confirm('一般社員が選択されていません。\n本当によろしいですか?');
                if (!bool) {
                    e.preventDefault();
                }
            })
        })
    </script>
    {% endif %} {% endblock %}
</body>

</html>

createDep/templates/createDep/newDep.html
{% extends 'createDep/base.html' %}
{% load static %}
<html lang="ja">

{% block title %}
    部署作成
{% endblock %}

<head>
    {% block addCSS %}
        <link rel="stylesheet" href="{% static 'createDep/css/newDep.css' %}">
    {% endblock %}

    <title>list</title>
    <meta charset="UTF-8">
    {#    <link rel="stylesheet" href="../../static/createDep/css/bootstrap.min.css">#}
    {#    <link rel="stylesheet" href="../../static/createDep/css/bootstrap.min.css.map">#}
    {#    <link rel="stylesheet" href="../../static/createDep/css/newDep.css">#}
</head>

<body>
{% block body %}
    <div class="overflow">
        <div class="d-grid gap-2">
            <form action="{% url 'dep:create' %}" method="post">{% csrf_token %}
                <h1>部署作成</h1>
                {% if dep_name %}
                    <input type="text" name="dep_name" id="dep_name" class="form-control-lg"
                           value="{{ dep_name }}">
                {% else %}
                    <input type="text" name="dep_name" id="dep_name" class="form-control-lg" placeholder="部署名">
                {% endif %}
                <button class="btn btn-secondary" name="select">所属社員</button>
                {# onclick="location.href=&quot;{% url "dep:user-list" %}&quot;" #}
                <div class=" group_btn d-flex justify-content-end">
                    <button class="btn btn-primary back_btn" name="back">戻る</button>
                    <button class="btn btn-primary create_btn" name="create" id="create">作成</button>
                </div>
            </form>
        </div>
    </div>
{% endblock %}

{#<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>#}
{#<script src="../../static/createDep/js/bootstrap.min.js"></script>#}
{#<script src="../../static/createDep/js/bootstrap.min.js.map"></script>#}
{% block addJS %}
    {% if alert %}
        <script>
            $(function () {
                {% if 'no_name' in alert %}
                    window.alert("{{ '部署名が入力されていません。' }}");
                {% endif %}
                {% if 'no_checked' in alert %}
                    $("#create").on('click', function (e) {
                        let bool = window.confirm('一般社員が選択されていません\n本当によろしいですか？');
                        if (!bool) {
                            e.preventDefault();
                        }
                    })
                {% endif %}
            })
        </script>
    {% endif %}
{% endblock %}
</body>
</html>

createDep/templates/createDep/positionList.html
{% extends 'createDep/base.html' %}
{% load static %}
<html lang="ja">

{% block title %}
    役職選択
{% endblock %}

<head>
    {% block addCSS %}
        <link rel="stylesheet" href="{% static 'createDep/css/position.css' %}">
    {% endblock %}

    <title>position</title>
    <meta charset="UTF-8">
    {#    <link rel="stylesheet" href="../../static/createDep/css/bootstrap.min.css">#}
    {#    <link rel="stylesheet" href="../../static/createDep/css/bootstrap.min.css.map">#}
    {#    <link rel="stylesheet" href="../../static/createDep/css/position.css">#}
</head>

<body>
{% block body %}
    <div class="overflow">
        <form action="{% url 'dep:position-list' num %}" method="POST">
            <div class="d-grid gap-2">
                <h1>役職選択</h1>
                <a href="{% url 'dep:user-list' num %}" class="link"
                   methods="POST">一般社員の部署割り当てを解除する場合はこちら</a>
                {% csrf_token %}
                <button class="btn btn-primary" name="director" value="director" id="director">
                    <div class="div_in_position_name">部長 :</div>
                    <div class="div_in_text">
                        <div class="text align-middle"><span>{% if dr.last_name and dr.first_name %}{{ dr.last_name }}
                            {{ dr.first_name }}{% else %}該当者なし{% endif %}</span></div>
                    </div>
                </button>
                <button class="btn btn-primary" name="chief" value="chief" id="chief">
                    <div class="div_in_position_name">主任 :</div>
                    <div class="div_in_text">
                        <div class="text align-middle">現在<span>{% if chf != 0 %}{{ chf }}名{% else %}
                            該当者なし{% endif %}</span>
                        </div>
                    </div>
                </button>
                <button class="btn btn-primary" name="employee" value="employee" id="employee">
                    <div class="div_in_position_name">一般社員 :</div>
                    <div class="div_in_text">
                        <div class="text align-middle">現在<span>{% if emp != 0 %}{{ emp }}名{% else %}
                            該当者なし{% endif %}</span></div>
                    </div>
                </button>
                <button class="btn back_btn float-end" name="back">戻る
                </button>
            </div>
        </form>
    </div>
{% endblock %}

{#<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>#}
{#<script src="../../static/createDep/js/bootstrap.min.js"></script>#}
{#<script src="../../static/createDep/js/bootstrap.min.js.map"></script>#}
{% block addJS %}
    <script>
        $(function () {
            $("#chief").on("click", function (e) {
                if ({{ dr.last_name }} &&
                {{ dr.first_name }})
                {
                    window.alert('部長が選択されていません。\n部長を選択してください。');
                    e.preventDefault();
                }
            })
            $("#employee").on('click', function (e) {
                if ({{ chf }} == 0
            )
                {
                    window.alert('主任が選択されていません。\n主任を選択してください。');
                    e.preventDefault();
                }
            })
        })
    </script>
{% endblock %}
</body>
</html>

createDep/templates/createDep/selectUser.html
{% load static %}
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <title>社員選択</title>
    <link rel="stylesheet" href="{% static 'createDep/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'createDep/css/bootstrap.min.css.map' %}">
    <link rel="stylesheet" href="{% static 'createDep/css/selectUser.css' %}">

    <!-- <link rel="stylesheet" href="../../static/createDep/css/bootstrap.min.css">
    <link rel="stylesheet" href="../../static/createDep/css/bootstrap.min.css.map">
    <link rel="stylesheet" href="../../static/createDep/css/selectUser.css"> -->

</head>
<body>
<div class="table_div">
    <h2>社員一覧</h2>
    <table class="table table-bordered" id="user_list_table">
        <tr class="th_row">
            <th class="th_id th">社員ID</th>
            <th class="th_name th">名前</th>
            <th class="th_dep th">部署</th>
            <th class="th_position th">役職</th>
            <th class="th_lift th">解除</th>
        </tr>
        {% if not flg %}
            <form id="form" action="{% url 'dep:create' %}">
        {% elif 'dr' in flg %}
            <form id="form" action="{% url 'dep:director' num %}">
        {% elif 'chf' in flg %}
            <form id="form" action="{% url 'dep:chief' num %}">
        {% elif 'emp' in flg %}
            <form id="form" action="{% url 'dep:employee-2' num %}">
        {% elif 'delete' in flg %}
            <form id="form" action="{% url 'dep:user-list' num %}">
        {% endif %}
        {% for array in user_array %}
            {% if array.user_id in checked %}
                <tr class="tr_main tr_main_gray">
                    <td class="td_id">{{ array.user_id }}</td>
                    <td class="td_name">{{ array.last_name }}{{ array.first_name }}</td>
                    <td class="td_dep">{{ array.department.department_name }}</td>
                    <td class="td_position">{{ array.position.position_name }}</td>
                    <td class="td_lift form-check"><input type="checkbox" class="form-check-input" name="cb"
                                                          value="{{ array.user_id }}" checked>
                    </td>
                </tr>
            {% else %}
                <tr class="tr_main">
                    <td class="td_id">{{ array.user_id }}</td>
                    <td class="td_name">{{ array.last_name }}{{ array.first_name }}</td>
                    <td class="td_dep">{{ array.department.department_name }}</td>
                    <td class="td_position">{{ array.position.position_name }}</td>
                    <td class="td_lift form-check"><input type="checkbox" class="form-check-input" name="cb"
                                                          value="{{ array.user_id }}">
                    </td>
                </tr>
            {% endif %}
        {% endfor %}
        <input type="checkbox" name="cb" value="00000000" hidden checked>
        </form>
    </table>
</div>
<div class="search_div">
    <h2>検索</h2>
    <div class="form-check">
        <input type="text" id="searchText" class="form-control form-control-lg input_text" placeholder="名前">
        <div class="input_checkbox">
            <input type="checkbox" name="" id="check_from" class="form-check-input input_checkbox">
            <label class="form-check-label" for="check_from">
                未所属
            </label>
        </div>
    </div>
    <button type="submit" class="btn btn-primary btn-1" id="search">
        検索
    </button>
    <button type="submit" class="btn btn-primary btn-2" form="form">
        決定
    </button>
    <button type="submit" class="btn btn-primary btn-3" onclick="location.href='{{ request.META.HTTP_REFERER }}'">
        戻る
    </button>
</div>


<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
<!-- <script src="../../static/createDep/js/bootstrap.min.js"></script>
<script src="../../static/createDep/js/bootstrap.min.js.map"></script>
<script src="../../static/createDep/js/selectUser.js"></script> -->
<script src="{% static 'createDep/js/bootstrap.min.js' %}"></script>
<script src="{% static 'createDep/js/bootstrap.min.js.map' %}"></script>
<script src="{% static 'createDep/js/selectUser.js' %}"></script>
<script>
    $(function () {
        $(".tr_main").each(function (index, element) {
            if (element.children[2].textContent === '未所属') {
                $(this).addClass('disable_check');
            }
        })
        $("#search").on('click', function () {
            console.log('click');
            {#表示しないtrにdisable_listクラスを付与する#}
            let searchText = $("#searchText").val();
            $(".tr_main").removeClass('disable_list');
            if (searchText) {
                console.log('ok');
                $(".tr_main").each(function (index, element) {
                    {#console.log($(this).children().children('.td_name'));#}
                    console.log(element.children[1].textContent);
                    if (element.children[1].textContent.indexOf(searchText)) {
                        $(this).addClass('disable_list');
                    }
                })
            } else {
                $(".tr_main").removeClass("disable_list");
                console.log("no match");
            }
        })
        {#    checkbox の判定 #}
        $("#check_from").on("click", function () {
            if ($("#check_from").prop('checked') == true) {
                $(".tr_main").each(function (index, element) {
                    if (element.children[2].textContent !== '未所属') {
                        $(this).addClass('disable_check');
                    } else {
                        $(this).toggleClass('disable_check');
                    }
                })
            } else {
                $(".tr_main").toggleClass("disable_check");
            }
        })
    })
</script>
</body>
</html>