Team2021/urls.py
from django.contrib import admin
from django.conf.urls import include
from django.urls import path

urlpatterns = [
    path('', include('login.urls')),
    path('admin/', admin.site.urls),
    path('create/', include('createRingisyo.urls')),
    path('account/', include('createAccount.urls')),
    path('dep/', include('createDep.urls')),
    path('position/', include('position.urls')),
    path('login/', include('login.urls')),
    path('list/', include('ringiList.urls')),
    path('top/', include('topPage.urls')),
    path('common/', include('common.urls')),
]

createDep/urls.py
from django.urls import path
from createDep import views

app_name = 'dep'

urlpatterns = [
    path('create/', views.create, name='create'),
    path('dep-list/', views.dep_list, name='dep-list'),
    path('position-list/<int:num>/', views.position_list, name='position-list'),
    path('director/<int:num>/', views.director, name='director'),
    path('chief/<int:num>/', views.chief, name='chief'),
    path('employee-1/<int:num>/', views.employee_1, name='employee-1'),
    path('employee-2/<int:num>/', views.employee_2, name='employee-2'),
    path('user-list/<int:num>/', views.user_list, name='user-list'),
    path('', views.top, name='top')
    #     position-list,
]

createRingisyo/urls.py
from django.urls import path
from createRingisyo import views

app_name = 'create'

urlpatterns = [
    path('', views.create, name='create'),
    path('check/', views.check, name='check'),
]

login/urls.py
from django.urls import path
from login import views

app_name = 'login'

urlpatterns = [
    # .../account/にアクセスがあった時、views.pyのindex関数を呼び出す
    path('', views.login, name='login'),
    path('first/', views.first, name='first'),
    path('logout/', views.logout, name='logout')
]

ringiList/urls.py
from django.urls import path
from ringiList import views

app_name = 'ringiList'

urlpatterns = [
    # .../account/にアクセスがあった時、views.pyのindex関数を呼び出す
    path('director/<int:approval_id>/', views.director_index, name='director'),
    path('chief/<int:approval_id>/', views.chief_index, name='chief'),
    path('employee/<int:approval_id>/', views.employee_index, name='employee'),
    path('mdirector/<int:approval_id>/', views.mdirector_index, name='mdirector'),
    path('president/<int:approval_id>/', views.president_index, name='president'),
    path('yesapproval/<int:approval_id>/', views.shounin, name='shounin'),
    path('noapproval/<int:approval_id>/', views.hiketu, name='hiketu'),
    path('created/<int:approval_id>/', views.sakuseizumi_kobetu, name='sakuseizumikobetu'),
    path('approved/<int:approval_id>/', views.shouninzumi_kobetu, name='shouninzumikobetu'),
    path('cancel/<int:approval_id>/', views.tekkai, name='tekkai'),
    # path('', views.remarks, name='remarks'),
    path('viewList/<str:check_text>/', views.get_list, name='list'),
    path('', views.back, name='back'),
]

topPage/urls.py
from django.urls import path
from topPage import views

app_name = 'topPage'

urlpatterns = [
    # .../account/にアクセスがあった時、views.pyのindex関数を呼び出す
    path('', views.top_page, name='topPage_index'),
]



# path('', views.Ringikobetu, name='ringi_kobetu')
# ringiview:ringi_kobetu  <int:your-args>
# 変数を渡すときは、pathの第一引数の''に書く<型: 変数名>

ringiList/models.py
from django.db import models

# Create your models here.

ringiList/views.py
from django.shortcuts import render
from common.models import *
from django.db.models import Q


# Create your views here.


def president_index(request, approval_id):
    login_user = request.session['user_data']
    approval = Approval.objects.get(approval_id=approval_id)
    user_data = User.objects.get(user_id=login_user)
    remarks = Remarks.objects.filter(approval_id=approval_id)
    context = {
        'approval': approval,  # 引数の稟議書IDと一致する稟議書データ
        'ringi_id': approval_id,  # 稟議書ID
        'user_data': user_data.position_id,  # 役職ID
        'remarks': remarks,
    }
    return render(request, 'ringiList/mati_one.html', context)


def mdirector_index(request, approval_id):
    login_user = request.session['user_data']
    user_data = User.objects.get(user_id=login_user)
    approval = Approval.objects.get(approval_id=approval_id)
    remarks = Remarks.objects.filter(approval_id=approval_id)
    context = {
        'approval': approval,
        'ringi_id': approval_id,
        'user_data': user_data.position_id,
        'remarks': remarks,
    }
    return render(request, 'ringiList/mati_one.html', context)


def director_index(request, approval_id):
    login_user = request.session['user_data']
    user_data = User.objects.get(user_id=login_user)
    approval = Approval.objects.get(approval_id=approval_id)
    remarks = Remarks.objects.filter(approval_id=approval_id)
    context = {
        'approval': approval,  # 引数の稟議書IDと一致する稟議書データ
        'ringi_id': approval_id,  # 稟議書ID
        'user_data': user_data.position_id,  # 役職ID
        'remarks': remarks,
    }
    return render(request, 'ringiList/mati_one.html', context)


def chief_index(request, approval_id):
    login_user = request.session['user_data']
    user_data = User.objects.get(user_id=login_user)
    approval = Approval.objects.get(approval_id=approval_id)
    remarks = Remarks.objects.filter(approval_id=approval_id)
    context = {
        'approval': approval,
        'ringi_id': approval.approval_id,
        'user_data': user_data.position_id,
        'remarks': remarks,
    }
    return render(request, 'ringiList/mati_one.html', context)


def employee_index(request, approval_id):
    login_user = request.session['user_data']
    user_data = User.objects.get(user_id=login_user)
    approval = Approval.objects.filter(approval_id=approval_id).reverse()
    context = {
        'approval': approval,
        'ringi_id': approval_id,
        'user_data': user_data.position_id,
    }
    return render(request, 'ringiList/sakuseizumi_kobetu.html', context)


def sakuseizumi_kobetu(request, approval_id):
    login_user = request.session['user_data']
    user_data = User.objects.get(user_id=login_user)
    approval = Approval.objects.get(approval_id=approval_id)
    remarks = Remarks.objects.filter(approval_id=approval_id)
    print(remarks)
    context = {
        'approval': approval,  # 受け取った稟議書idと一致する稟議書データ
        'ringi_id': approval_id,
        'user_data': user_data.position_id,
        'last_name': user_data.last_name,  # 記入者の苗字
        'first_name': user_data.first_name,  # 記入者の名前
        'remarks': remarks,
    }
    return render(request, 'ringiList/sakuseizumi_kobetu.html', context)


def shouninzumi_kobetu(request, approval_id):
    login_user = request.session['user_data']
    position = User.objects.get(user_id=login_user)
    approval = Approval.objects.get(approval_id=approval_id)
    remarks = Remarks.objects.filter(approval_id=approval_id)
    context = {
        'approval': approval,
        'ringi_id': approval_id,
        'position_id': position.position_id,
        'remarks': remarks,
    }
    return render(request, 'ringiList/shouninzumi_kobetu.html', context)
    # 自分より上の役職の人が承認したら撤回できないようにする。html上にif文で書く


def hiketu(request, approval_id):
    print("否決されました")
    position = User.objects.get(pk=request.session['user_data']).position_id
    approval = Approval.objects.get(approval_id=approval_id)
    remarks = Remarks.objects.filter(approval_id=approval_id)
    context = {
        'approval': approval,
        'remarks': remarks,
        'position_id': position,
    }
    if position == 5:
        print("主任が否決")
        approval.p_chief = 2
        approval.save()
        #  ↑　主任の承認フラグを１に変える処理？書き方が合っているかは不明。
        # 主任の承認フラグを変える
    if position == 4:
        approval.p_director = 2
        approval.save()
    # 部長の承認フラグを変える
    if position == 3:
        approval.p_mdirectop = 2
        approval.save()
    # 常務の承認フラグを変える
    if position == 2:
        approval.p_president = 2
        approval.save()
    # 社長の承認フラグを変える
    # 稟議書を否決する処理、引数として、稟議書IDと役職IDを受け取って、役職IDに一致する役職者の承認フラグを変える
    # ただ、承認待ち個別の画面で、否決ボタンを押したときに変数を二つ渡す方法がわからない。
    return render(request, 'ringiList/shouninzumi_kobetu.html', context)


def shounin(request, approval_id):
    print("承認されました")
    position = User.objects.get(pk=request.session['user_data']).position_id
    approval = Approval.objects.get(approval_id=approval_id)
    remarks = Remarks.objects.filter(approval_id=approval_id)
    context = {
        'approval': approval,
        'remarks': remarks,
        'position_id': position,
    }
    if position == 5:
        approval.p_chief = 1
        approval.save()
    # 主任の承認フラグを変える
    if position == 4:
        approval.p_director = 1
        approval.save()
    # 部長の承認フラグを変える
    if position == 3:
        print('ok')
        approval.p_mdirectop = 1
        approval.save()
    # 常務の承認フラグを変える
    if position == 2:
        approval.p_president = 1
        approval.save()
    # 社長の承認フラグを変える
    return render(request, 'ringiList/shouninzumi_kobetu.html', context)


def tekkai(request, approval_id):
    position = User.objects.get(pk=request.session['user_data']).position_id
    approval = Approval.objects.get(approval_id=approval_id)
    context = {
        'approval': approval,
    }
    if position == 5:
        approval.p_chief = 0
        approval.save()
    if position == 4:
        approval.p_director = 0
        approval.save()
    if position == 3:
        approval.p_mdirectop = 0
        approval.save()
    if position == 2:
        approval.p_president = 0
        approval.save()
    return render(request, 'ringiList/mati_one.html', context)


"""
def remarks(request):
    request.get['remarks']
"""


def get_list(request, check_text):
    if check_text == "create":  # 作成済み一覧へ遷移
        login_user = request.session['user_data']
        approval = Approval.objects.filter(user_id=login_user).reverse()
        context = {
            'approval': approval,  # 作成者がログインユーザと一致する稟議書データ
        }
        return render(request, 'ringiList/sakuseizumi_list.html', context)

    elif check_text == "pend":  # 承認待ち一覧へ遷移
        login_user = request.session['user_data']
        user_data = User.objects.get(user_id=login_user)
        request.session['position_id'] = user_data.position_id
        president = Approval.objects.filter(Q(p_chief=1), Q(p_director=1), Q(p_mdirectop=1), Q(p_president=0),
                                            ~Q(user__user_id=login_user)).reverse()

        mdirector = Approval.objects.filter(Q(p_chief=1), Q(p_director=1), Q(p_mdirectop=0),
                                            ~Q(user__user_id=login_user)).reverse()

        director = Approval.objects.filter(Q(p_chief=1), Q(p_director=0), ~Q(user__user_id=login_user),
                                           Q(user__department_id=user_data.department_id))

        chief = Approval.objects.filter(Q(p_chief=0), ~Q(user__user_id=login_user),
                                        Q(user__department_id=user_data.department_id))

        employee = Approval.objects.all().filter(Q(p_chief=0), Q(user__user_id=login_user),
                                                 Q(user__department_id=user_data.department_id))

        for i in chief:
            print(i.user.user_id, i.user.position_id)

        context = {
            'president': president,
            'mdirector': mdirector,
            'director': director,
            'chief': chief,
            'employee': employee,
            'user_data': user_data.position_id,
        }
        return render(request, 'ringiList/shouninmati_list.html', context)

    elif check_text == "pended":  # 承認済み一覧へ遷移
        login_user = request.session['user_data']
        user_data = User.objects.get(user_id=login_user)
        president = Approval.objects.all().filter(Q(p_president=1) | Q(p_president=2)).reverse()
        mdirector = Approval.objects.all().filter(Q(p_mdirectop=1) | Q(p_mdirectop=2)).reverse()
        director = Approval.objects.all().filter(Q(p_director=1) | Q(p_mdirectop=2),
                                                 Q(user__department_id=user_data.department_id))
        chief = Approval.objects.filter(Q(p_chief=1) | Q(p_chief=2),
                                        Q(user__department_id=user_data.department_id))
        context = {
            'president': president,  # 社長が承認した稟議書の全データ
            'mdirector': mdirector,  # 常務が承認した稟議書の全データ
            'director': director,  # 部長が承認した稟議書の全データ
            'chief': chief,  # 主任が承認した稟議書の全データ
            'user_data': user_data.position_id,  # ログインしたユーザの役職ID
        }
        return render(request, 'ringiList/shouninzumi_list.html', context)

    #  稟議書を承認する処理、引数として、稟議書IDと役職IDを受け取って、役職IDに一致する役職者の承認フラグを変える


def back(request):
    user_data = User.objects.get(user_id=request.session['user_data'])
    data = Approval.objects.all()

    context = {
        'user_data': user_data,
        'data': data,
        'model': get_Approval_query(request.session['user_data'])
    }

    return render(request, 'topPage/topPage.html', context)


"""   稟議書の支払い総額によって、どの役職までの人が承認するのか決める方法がわからない   """

ringiList/templates/ringiList/base.html
{% load static %}

<html lang="ja">

<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'topPage/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'topPage/css/bootstrap.min.css.map' %}">
    <link rel="stylesheet" href="{% static 'topPage/css/base.css' %}">
    {% block addCSS %}{% endblock %}
</head>

<body>
<header id="header" class="sticky-top">
    <div class="flex-row navbar align-items-center">
        <div id="header_title" class="col">
            <a href="{% url 'topPage:topPage_index' %}">稟議書システム</a>
        </div>
        <div class="ml-auto d-flex right_row">
            <div class="col dropdown">
                <button type="button" class="btn btn-secondary dropdown-toggle" data-bs-toggle="dropdown"
                        id="dropdown_button1" aria-expanded="false">
                    作成
                </button>
                {% if request.session.user_info.position_id == 6 or request.session.user_info.position_id == 5 %}
                    <ul class="dropdown-menu" aria-labelledby="dropdown_button2">
                        <li><a class="dropdown-item" href="{% url 'create:create' %}">稟議書</a></li>
                    </ul>

                {% elif request.session.user_info.position_id == 1 %}
                    <ul class="dropdown-menu" aria-labelledby="dropdown_button1">
                        <li><a class="dropdown-item" href="{% url 'dep:create' %}">部署</a></li>
                    </ul>
                    <ul class="dropdown-menu" aria-labelledby="dropdown_button1">
                        <li><a class="dropdown-item" href="#">アカウント</a></li>
                    </ul>
                {% endif %}


            </div>
            <div class="col dropdown">
                <button type="button" class="btn btn-secondary dropdown-toggle" data-bs-toggle="dropdown"
                        id="dropdown_button2" aria-expanded="false">
                    一覧
                </button>
                {% if request.session.user_info.position_id == 6 %}
                    <ul class="dropdown-menu" aria-labelledby="dropdown_button2">
                        <li><a class="dropdown-item" href="{% url 'ringiList:list' "create" %}">作成物</a></li>
                    </ul>
                {% elif request.session.user_info.position_id == 5 %}
                    <ul class="dropdown-menu" aria-labelledby="dropdown_button2">
                        <li><a class="dropdown-item" href="{% url 'ringiList:list' "create" %}">作成物</a></li>
                        <li><a class="dropdown-item" href="{% url 'ringiList:list' "pend" %}">承認待ち</a></li>
                        <li><a class="dropdown-item" href="{% url 'ringiList:list' "pended" %}">承認済み</a></li>
                    </ul>

                {% elif request.session.user_info.position_id <= 4 %}
                    <ul class="dropdown-menu" aria-labelledby="dropdown_button2">
                        <li><a class="dropdown-item" href="{% url 'ringiList:list' "pend" %}">承認待ち</a></li>
                        <li><a class="dropdown-item" href="{% url 'ringiList:list' "pended" %}">承認済み</a></li>
                    </ul>
                {% elif request.session.user_info.position_id == 1 %}
                    <ul class="dropdown-menu" aria-labelledby="dropdown_button2">
                        <li><a class="dropdown-item" href="{% url 'dep:dep-list' %}">部署一覧</a></li>
                    </ul>
                {% endif %}
            </div>
            <div class="col">
                <div class="info_1">{{ request.session.user_name }}</div>
                <a href="{% url 'login:logout' %}" class="info_2">ログアウト</a>
            </div>
        </div>
    </div>
</header>
<main id="main">
    {% block body %}
        {{ request.session.user_info }}
    {% endblock %}
</main>
<footer id="footer">
    <div class="footer_toplink">
        <a href="#header" class="d-flex flex-column justify-content-center">
            トップへ戻る
        </a>
    </div>
    <div class="footer_infodiv">
        <div class="footer_copyright  position-relative">
            <p class="position-absolute top-50 start-50 translate-middle">&copy;2021 morijyobi</p>
            <a href="#" class="position-absolute top-50 end-0 translate-middle">ログアウト</a>
        </div>
    </div>
</footer>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
<script src="{% static 'topPage/js/bootstrap.min.js' %}"></script>
<script src="{% static 'topPage/js/bootstrap.min.js.map' %}"></script>
{% block addJS %}{% endblock %}
</body>

</html>

ringiList/templates/ringiList/mati_one.html
{% extends "ringiList/base.html" %}
{% load static %}

{% block body %}
    <head>
        <meta charset="UTF-8">
        <link rel="stylesheet" href="{% static 'ringiList/css/02.css' %}">
        <link rel="stylesheet" href="{% static 'ringiList/css/02_border.css' %}">
        <link rel="stylesheet" href="{% static 'ringiList/css/02_sub.css' %}">
        <link rel="stylesheet" type="text/css" href="http://yui.yahooapis.com/3.18.1/build/cssreset/cssreset-min.css">
        <title>Document</title>
    </head>

    <body>
    <div class="main_div_ringisyo">
        <div class="ringisyo_area">
            <div class="title_area">
                <h1>承認待ち稟議書</h1>
            </div>
            <div class="info_area">
                <div class="writer_area">
                    <!-- dateに作成日付を自動入力 -->
                    <div class="docs_type">
                        <div>文書種別</div>
                        <div>支払 社長 総額100万円以上、常務取締 総額30万円以上、部長30万円未満</div>
                    </div>
                    <div class="date">
                        <div>承認期限</div>
                        <div id="date">{{ approval.limited }}</div>
                        <!-- 承認期限を自動入力 -->
                    </div>
                </div>
                <div class="info_space"></div>
                <div class="auth_area">
                    <!-- 作成者から所属部署、部長を自動入力 -->
                    <div class="dep_title">起案部署</div>
                    <div class="dep_name">
                        <div class="dep_1">部署名</div>
                        <div class="dep_2" id="dep_name">
                        </div>
                        <!--部署名を入力-->
                    </div>
                    <div class="person_name">
                        <div class="position_name">
                            <div class="position_1">責任者</div>
                            <div></div>
                            <div></div>
                            <div class="position_2">記入者</div>
                        </div>
                        <div class="position_person">
                            <div class="position_person_1">
                            </div>
                            <!--所属部署の部長名を入力-->
                            <div></div>
                            <div></div>
                            <div class="position_person_2">
                                <!-- 作成者が入る -->
                            </div>
                            <!--作成者名を入力-->
                        </div>
                    </div>
                </div>
            </div>
            <div></div>
            <div class="docs_title_area">
                <!-- 稟議書の件名(タイトル) -->
                <div class="docs_title_input">
                    <div class="left_padding">件名</div>
                    <div class="docs_input">{{ approval.title }}</div>
                </div>
                <div class="docs_title_space">
                    <div></div>
                    <div></div>
                </div>
            </div>
            <div class="pay_info_area">
                <!-- 賞品総額と商品名を自動入力 -->
                <div class="pay_all">
                    <div class="left_padding">支払総額</div>
                    <div id="pay_all">{{ approval.price }}</div>
                </div>
                <div class="pay_product">
                    <div class="left_padding top_padding">内容:</div>
                    <div id="pay_product"></div>
                </div>
            </div>
            <div class="trader_info_area">
                <!-- 商品名と業者名を自動入力 -->
                <div class="left_padding top_padding"> 1, 商品名:</div>
                <div class="product_name">{{ approval.goods }}</div>
                <!-- 商品名を入力 -->
                <div class="left_padding top_padding"> 2, 業者名:</div>
                <div class="trader_name">{{ approval.trader }}</div>
                <!-- 業者名を入力 -->
            </div>
            <div class="reason_area">
                <!-- 必要理由を自動入力 -->
                <div class="left_padding">3, 必要理由</div>
                <div id="reason_text">{{ approval.necessity_reason }}</div>
                <!-- 必要理由を自動入力 -->
            </div>
            <div class="trader_reason_area">
                <!-- 業者選定理由を入力 -->
                <div class="left_padding"> 4, 業者選定理由</div>
                <div id="trader_reason_area">{{ approval.trader_reason }}</div>
                <!-- 業者選定理由を入力 -->
            </div>
            <div class="remarks">
                <!-- 備考を自動入力 -->
                <div class="left_padding"> 5, 備考</div>
                <div id="remarks">
                    <input type="text" size="40" maxlength="30" values="memo">
                    <button type='submit'>記入</button>
                    {% for remark in remarks %}
                        {{ remark.remarks }}
                    {% endfor %}
                </div>
                <!-- 備考を自動入力 -->
            </div>

            <!-- ボタン部分 -->
            <div></div>
            <div class="bottom_area">
                <div class="approval">
                    <div class="position">主任</div>
                    <div class="position">部長</div>
                    <div class="position">常務取締役</div>
                    <div class="position">社長</div>
                    <div class="decision_1">
                        {% if approval.p_chief == 1 %}
                            <p style="font-size:35px">&nbsp&nbsp〇</p>
                        {% elif approval.p_chief == 2 %}
                            <p style="font-size:35px">&nbsp&nbsp✖</p>
                        {% endif %}
                    </div>
                    <div class="decision_2">
                        {% if approval.p_director == 1 %}
                            <p style="font-size:35px">&nbsp&nbsp〇</p>
                        {% elif approval.p_director == 2 %}
                            <p style="font-size:35px">&nbsp&nbsp✖</p>
                        {% endif %}
                    </div>
                    <div class="decision_3">
                        {% if approval.p_mdirectop == 1 %}
                            <p style="font-size:35px">&nbsp&nbsp〇</p>
                        {% elif approval.p_mdirectop == 2 %}
                            <p style="font-size:35px">&nbsp&nbsp✖</p>
                        {% endif %}
                    </div>
                    <div class="decision_4">
                        {% if approval.p_president == 1 %}
                            <p style="font-size:35px">&nbsp&nbsp〇</p>
                        {% elif approval.p_president == 2 %}
                            <p style="font-size:35px">&nbsp&nbsp✖</p>
                        {% endif %}
                    </div>
                </div>
                <!-- 作成時、作成者確認時には不要 -->
                <div></div>
                <div class="button">
                    <div class="docs_button">
                        <input type="button" onclick="location.href='{% url 'ringiList:hiketu' approval.approval_id %}'"
                           value="   否決   " style="font-size:25px;">
                    </div>
                    <div class="docs_button">
                        <input type="button" onclick="location.href='{% url 'ringiList:shounin' approval.approval_id %}'"
                           value="   承認   " style="font-size:25px;">
                    </div>
                </div>

            </div>
            <div></div>
        </div>
    </div>
    </body>

{% endblock %}

ringiList/templates/ringiList/sakuseizumi_list.html
{% extends "ringiList/base.html" %}
{% load static %}

{% block body %}
<div class="center">
    <div class="center">
            <h1>作成済み一覧</h1>
    <!-- form -->
            <p>　</p>
            {% for array in approval %}
                <button onclick="location.href=&quot;{% url 'ringiList:sakuseizumikobetu' array.approval_id %}&quot">
                    作成者:  {{ array.user.last_name }}{{ array.user.first_name }}
                    件名:  {{ array.title }}
                </button>
                <br>
                <br>
            {% endfor %}
    </div>
</div>
{% endblock %}

ringiList/templates/ringiList/shouninmati_list.html
{% extends "ringiList/base.html" %}
{% load static %}

{% block body %}
    <div class="center">
        <div class="center">
            <h1>承認待ち一覧</h1>
            <p>　</p>
            {% if user_data == 5 %} <!-- 主任だったら -->

                {% for array in chief %}
                    <form action="{% url 'ringiList:chief' array.approval_id %}" method="get">
                        <button type="submit">
                            作成者: {{ array.user.last_name }}{{ array.user.first_name }}
                            件名: {{ array.title }}
                        </button>
                        <br>
                        <br>
                    </form>
                {% endfor %}
            {% endif %}

            {% if user_data == 4 %} <!-- 部長だったら -->

                {% for array in director %}
                    <form action="{% url 'ringiList:director' array.approval_id %}" method="get">
                        <button type="submit">
                            作成者: {{ array.user.last_name }}{{ array.user.first_name }}
                            件名: {{ array.title }}
                        </button>
                        <br>
                    </form>
                {% endfor %}
            {% endif %}

            {% if user_data == 3 %} <!-- 常務だったら -->
                {% for array in mdirector %}
                    <form action="{% url 'ringiList:mdirector' array.approval_id %}" method="get">
                        <button type="submit">
                            作成者: {{ array.user.last_name }}{{ array.user.first_name }}
                            件名: {{ array.title }}
                        </button>
                        <br>
                    </form>
                {% endfor %}
            {% endif %}

            {% if user_data == 2 %} <!-- 社長だったら -->
                {% for array in president %}
                    <form action="{% url 'ringiList:president' array.approval_id %}" method="get">
                        <button type="submit">
                            作成者: {{ array.user.last_name }}{{ array.user.first_name }}
                            件名: {{ array.title }}
                        </button>
                        <br>
                    </form>
                {% endfor %}
            {% endif %}
        </div>
    </div>
{% endblock %}