Team2021/urls.py
from django.contrib import admin
from django.conf.urls import include
from django.urls import path

urlpatterns = [
    path('', include('login.urls')),
    path('admin/', admin.site.urls),
    path('create/', include('createRingisyo.urls')),
    path('account/', include('createAccount.urls')),
    path('dep/', include('createDep.urls')),
    path('position/', include('position.urls')),
    path('login/', include('login.urls')),
    path('list/', include('ringiList.urls')),
    path('top/', include('topPage.urls')),
    path('common/', include('common.urls')),
]

createDep/urls.py
from django.urls import path
from createDep import views

app_name = 'dep'

urlpatterns = [
    path('create/', views.create, name='create'),
    path('dep-list/', views.dep_list, name='dep-list'),
    path('position-list/<int:num>/', views.position_list, name='position-list'),
    path('director/<int:num>/', views.director, name='director'),
    path('chief/<int:num>/', views.chief, name='chief'),
    path('employee-1/<int:num>/', views.employee_1, name='employee-1'),
    path('employee-2/<int:num>/', views.employee_2, name='employee-2'),
    path('user-list/<int:num>/', views.user_list, name='user-list'),
    path('', views.top, name='top')
    #     position-list,
]

createRingisyo/urls.py
from django.urls import path
from createRingisyo import views

app_name = 'create'

urlpatterns = [
    path('', views.create, name='create'),
    path('check/', views.check, name='check'),
]

login/urls.py
from django.urls import path
from login import views

app_name = 'login'

urlpatterns = [
    # .../account/にアクセスがあった時、views.pyのindex関数を呼び出す
    path('', views.login, name='login'),
    path('first/', views.first, name='first'),
    path('logout/', views.logout, name='logout')
]

ringiList/urls.py
from django.urls import path
from ringiList import views

app_name = 'ringiList'

urlpatterns = [
    # .../account/にアクセスがあった時、views.pyのindex関数を呼び出す
    path('director/<int:approval_id>/', views.director_index, name='director'),
    path('chief/<int:approval_id>/', views.chief_index, name='chief'),
    path('employee/<int:approval_id>/', views.employee_index, name='employee'),
    path('mdirector/<int:approval_id>/', views.mdirector_index, name='mdirector'),
    path('president/<int:approval_id>/', views.president_index, name='president'),
    path('yesapproval/<int:approval_id>/', views.shounin, name='shounin'),
    path('noapproval/<int:approval_id>/', views.hiketu, name='hiketu'),
    path('created/<int:approval_id>/', views.sakuseizumi_kobetu, name='sakuseizumikobetu'),
    path('approved/<int:approval_id>/', views.shouninzumi_kobetu, name='shouninzumikobetu'),
    path('cancel/<int:approval_id>/', views.tekkai, name='tekkai'),
    # path('', views.remarks, name='remarks'),
    path('viewList/<str:check_text>/', views.get_list, name='list'),
    path('', views.back, name='back'),
]

topPage/urls.py
from django.urls import path
from topPage import views

app_name = 'topPage'

urlpatterns = [
    # .../account/にアクセスがあった時、views.pyのindex関数を呼び出す
    path('', views.top_page, name='topPage_index'),
]



# path('', views.Ringikobetu, name='ringi_kobetu')
# ringiview:ringi_kobetu  <int:your-args>
# 変数を渡すときは、pathの第一引数の''に書く<型: 変数名>

createRingisyo/views.py
import requests
from django.shortcuts import render, redirect
from common.models import *
from Team2021 import slack_message as s_m_send
from datetime import datetime, timedelta


# Create your views here.


def create(request):
    # ここの機能でのみ、user_formerセッションを使用する
    # user_former = User.objects.get(pk=90000200)
    # request.session['user_former'] = user_former

    # 結合時に上をコメントアウト
    user_former = User.objects.get(pk=request.session['user_data'])
    request.session['user_former'] = user_former
    context = {'user_former': user_former}

    if 'context' in request.session:
        print('check context')
        print(context)
        context = request.session['context']
        del request.session['context']

    boss_data = User.objects.get(pk=user_former.boss_id)
    if request.method == 'POST':
        redirect('login:login')
    elif request.method == 'GET':
        if 'back' in request.GET:
            print(context)
            return render(request, 'createRingisyo/create.html', context)
        if 'user_former' in request.session:
            if 'edit' in request.GET:
                limit = request.GET['limit']
                title = request.GET['title']
                product_name = request.GET['product_name']
                trader_name = request.GET['trader_name']
                quantity = request.GET['quantity']
                unit_price = request.GET['unit_price']
                reason = request.GET['reason']
                trader_reason = request.GET['trader_reason']
                remarks = request.GET['remarks']
                context = {
                    'user_former': user_former,
                    'boss_former': boss_data,
                    'limit': limit,
                    'title': title,
                    'p_name': product_name,
                    't_name': trader_name,
                    'quantity': quantity,
                    'unit_price': unit_price,
                    'reason': reason,
                    't_reason': trader_reason,
                    'remarks': remarks
                }
                first_date = datetime.now()
                limit = limit.split('-')
                second_date = datetime(int(limit[0]), int(limit[1]), int(limit[2]))
                if first_date > second_date:
                    context['alert'] = "承認期限に、過去または今日の日付が入力されています"
                    return render(request, 'createRingisyo/create.html', context)
                elif len(title) < 1 or len(title) >= 33:
                    context['alert'] = "件名(表題)が1文字未満 もしくは 33文字以上となっています。"
                    return render(request, 'createRingisyo/create.html', context)
                elif len(product_name) < 1 or len(product_name) >= 33:
                    context['alert'] = "物品名が1文字未満 もしくは 33文字以上となっています。"
                    return render(request, 'createRingisyo/create.html', context)
                elif len(trader_name) < 1 or len(trader_name) >= 33:
                    context['alert'] = "業者名が1文字未満 もしくは 33文字以上となっています。"
                    return render(request, 'createRingisyo/create.html', context)
                elif is_not_int(quantity) and quantity != "一式":
                    context['alert'] = "数量に数値以外が入力されています。数量に使用できるのは、数値 または 一式 のみです。"
                    return render(request, 'createRingisyo/create.html', context)
                elif is_not_int(unit_price):
                    context['alert'] = "単価に数値以外が入力されています。単価に使用できるのは数値のみです。"
                    return render(request, 'createRingisyo/create.html', context)
                elif len(reason) < 1 or len(reason) >= 513:
                    context['alert'] = "必要理由が1文字未満 もしくは 512以上となっています。"
                    return render(request, 'createRingisyo/create.html', context)
                elif len(trader_reason) < 1 or len(trader_reason) >= 513:
                    context['alert'] = "業者選定理由が1文字未満 もしくは 512文字以上となっています。"
                    return render(request, 'createRingisyo/create.html', context)
                elif len(remarks) < 0 or len(remarks) >= 513:
                    context['alert'] = "備考が512文字以上となっています。"
                    return render(request, 'createRingisyo/create.html', context)

                if '一式' == quantity:
                    quantity = 1
                pay_all = int(quantity) * int(unit_price)
                context['pay_all'] = pay_all

                request.session['title'] = title
                request.session['limit'] = limit
                request.session['goods'] = product_name
                request.session['trader'] = trader_name
                request.session['quantity'] = quantity
                request.session['price'] = unit_price
                request.session['necessity_reason'] = reason
                request.session['trader_reason'] = trader_reason
                request.session['remarks'] = remarks

                request.session['context'] = context

                return render(request, 'createRingisyo/check.html', context)
            else:
                context = {'user_former': user_former}
                return render(request, 'createRingisyo/create.html', context)
    else:
        return redirect('login:login')


def check(request):
    if request.method == 'GET':
        if 'send' in request.GET:
            if 'user_former' in request.session:
                limit = request.session['limit']
                limit = datetime(int(limit[0]), int(limit[1]), int(limit[2]))
                approval = Approval(
                    title=request.session['title'],
                    user=request.session['user_former'],
                    limited=limit,
                    goods=request.session['goods'],
                    trader=request.session['trader'],
                    quantity=request.session['quantity'],
                    price=request.session['price'],
                    necessity_reason=request.session['necessity_reason'],
                    trader_reason=request.session['trader_reason'],
                    p_chief=0,
                    p_director=0,
                    p_mdirectop=0,
                    p_president=0
                )

                approval.save()

                Remarks.objects.create(
                    approval=approval,
                    user=request.session['user_former'],
                    remarks=request.session['remarks']
                )
                print('create all')
                # トップに戻る
                return redirect('topPage:topPage_index')


def is_not_int(s):
    try:
        int(s, 10)
    except ValueError:
        return True
    else:
        return False

createRingisyo/templates/createRingisyo/base.html
{% load static %}

<html lang="ja">

<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'topPage/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'topPage/css/bootstrap.min.css.map' %}">
    <link rel="stylesheet" href="{% static 'topPage/css/base.css' %}">
    {% block addCSS %}{% endblock %}
</head>

<body>
<header id="header" class="sticky-top">
    <div class="flex-row navbar align-items-center">
        <div id="header_title" class="col">
            <a href="{% url 'topPage:topPage_index' %}">稟議書システム</a>
        </div>
        <div class="ml-auto d-flex right_row">
            <div class="col dropdown">
                <button type="button" class="btn btn-secondary dropdown-toggle" data-bs-toggle="dropdown"
                        id="dropdown_button1" aria-expanded="false">
                    作成
                </button>
                {% if request.session.user_info.position_id == 6 or request.session.user_info.position_id == 5 %}
                    <ul class="dropdown-menu" aria-labelledby="dropdown_button2">
                        <li><a class="dropdown-item" href="{% url 'create:create' %}">稟議書</a></li>
                    </ul>

                {% elif request.session.user_info.position_id == 1 %}
                    <ul class="dropdown-menu" aria-labelledby="dropdown_button1">
                        <li><a class="dropdown-item" href="{% url 'dep:create' %}">部署</a></li>
                    </ul>
                    <ul class="dropdown-menu" aria-labelledby="dropdown_button1">
                        <li><a class="dropdown-item" href="#">アカウント</a></li>
                    </ul>
                {% endif %}


            </div>
            <div class="col dropdown">
                <button type="button" class="btn btn-secondary dropdown-toggle" data-bs-toggle="dropdown"
                        id="dropdown_button2" aria-expanded="false">
                    一覧
                </button>
                {% if request.session.user_info.position_id == 6 %}
                    <ul class="dropdown-menu" aria-labelledby="dropdown_button2">
                        <li><a class="dropdown-item" href="{% url 'ringiList:list' "create" %}">作成物</a></li>
                    </ul>
                {% elif request.session.user_info.position_id == 5 %}
                    <ul class="dropdown-menu" aria-labelledby="dropdown_button2">
                        <li><a class="dropdown-item" href="{% url 'ringiList:list' "create" %}">作成物</a></li>
                        <li><a class="dropdown-item" href="{% url 'ringiList:list' "pend" %}">承認待ち</a></li>
                        <li><a class="dropdown-item" href="{% url 'ringiList:list' "pended" %}">承認済み</a></li>
                    </ul>

                {% elif request.session.user_info.position_id <= 4 %}
                    <ul class="dropdown-menu" aria-labelledby="dropdown_button2">
                        <li><a class="dropdown-item" href="{% url 'ringiList:list' "pend" %}">承認待ち</a></li>
                        <li><a class="dropdown-item" href="{% url 'ringiList:list' "pended" %}">承認済み</a></li>
                    </ul>
                {% elif request.session.user_info.position_id == 1 %}
                    <ul class="dropdown-menu" aria-labelledby="dropdown_button2">
                        <li><a class="dropdown-item" href="{% url 'dep:dep-list' %}">部署一覧</a></li>
                    </ul>
                {% endif %}
            </div>
            <div class="col">
                <div class="info_1">{{ request.session.user_name }}</div>
                <a href="{% url 'login:logout' %}" class="info_2">ログアウト</a>
            </div>
        </div>
    </div>
</header>
<main id="main">
    {% block body %}
        {{ request.session.user_info }}
    {% endblock %}
</main>
<footer id="footer">
    <div class="footer_toplink">
        <a href="#header" class="d-flex flex-column justify-content-center">
            トップへ戻る
        </a>
    </div>
    <div class="footer_infodiv">
        <div class="footer_copyright  position-relative">
            <p class="position-absolute top-50 start-50 translate-middle">&copy;2021 morijyobi</p>
            <a href="#" class="position-absolute top-50 end-0 translate-middle">ログアウト</a>
        </div>
    </div>
</footer>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
<script src="{% static 'topPage/js/bootstrap.min.js' %}"></script>
<script src="{% static 'topPage/js/bootstrap.min.js.map' %}"></script>
{% block addJS %}{% endblock %}
</body>

</html>

createRingisyo/templates/createRingisyo/check.html
{% extends 'createRingisyo/base.html' %}
{% load static %}

<html lang="ja">
{% block title %}
    トップページ
{% endblock %}

<head>
    {% block addCSS %}
        <link rel="stylesheet" href="{% static 'createRingisyo/css/check_1.css' %}">
        <link rel="stylesheet" href="{% static 'createRingisyo/css/check_2.css' %}">
        <link rel="stylesheet" href="{% static 'createRingisyo/css/check_3.css' %}">

    {% endblock %}

    <title>トップページ</title>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="../../static/createRingisyo/css/bootstrap.min.css">
    <link rel="stylesheet" href="../../static/createRingisyo/css/bootstrap.min.css.map">
    <link rel="stylesheet" href="../../static/createRingisyo/css/">

</head>

<body>
{% block body %}
    <div class="overflow">
        <div class="d-gid gap-2">
            <div class="main_div_ringisyo">
                <div class="ringisyo_area">
                    <div class="title_area">
                        <h1>稟議書確認画面</h1>
                    </div>
                    <div class="info_area">
                        <div class="writer_area">
                            <!-- dateに作成日付を自動入力 -->
                            <div class="docs_type">
                                <div>文書種別</div>
                                <div>支払 社長 総額100万円以上、常務取締 総額30万円以上、 部長30万円未満</div>
                            </div>
                            <div class="date">
                                <div>承認期限</div>
                                <div id="date">{{ limit }}</div>
                                <!-- 承認期限を自動入力 -->
                            </div>
                        </div>
                        <div class="info_space"></div>
                        <div class="auth_area">
                            <!-- 作成者から所属部署、部長を自動入力 -->
                            <div class="dep_title">起案部署</div>
                            <div class="dep_name">
                                <div class="dep_1">部署名</div>
                                <div class="dep_2" id="dep_name">{{ user_former.department.department_name }}部
                                </div>
                                <!--部署名を入力-->
                            </div>
                            <div class="person_name">
                                <div class="position_name">
                                    <div class="position_1">責任者</div>
                                    <div></div>
                                    <div></div>
                                    <div class="position_2">記入者</div>
                                </div>
                                <div class="position_person">
                                    <div class="position_person_1">{{ boss_former.last_name }}<br>{{ boss_former.first_name }}
                                    </div>
                                    <!--所属部署の部長名を入力-->
                                    <div></div>
                                    <div></div>
                                    <div class="position_person_2">{{ user_former.last_name }}<br>{{ user_former.first_name }}
                                    </div>
                                    <!--作成者名を入力-->
                                </div>
                            </div>
                        </div>
                    </div>
                    <div></div>
                    <div class="docs_title_area">
                        <!-- 稟議書の件名(タイトル) -->
                        <div class="docs_title_input">
                            <div class="left_padding">件名</div>
                            <div class="docs_input">{{ title }}</div>
                        </div>
                        <div class="docs_title_space">
                            <div></div>
                            <div></div>
                        </div>
                    </div>
                    <div class="pay_info_area">
                        <!-- 賞品総額と商品名を自動入力 -->
                        <div class="pay_all">
                            <div class="left_padding">支払総額</div>
                            <div id="pay_all">{{ pay_all }}</div>
                        </div>
                        <div class="pay_product">
                            <div class="left_padding top_padding">内容:</div>
                            <div id="pay_product">下記の通り申請致しますので、ご決裁いただきたくお願い申し上げます。</div>
                        </div>
                    </div>
                    <div class="trader_info_area">
                        <!-- 商品名と業者名を自動入力 -->
                        <div class="left_padding top_padding"> 1, 商品名:</div>
                        <div class="product_name">{{ p_name }}</div>
                        <!-- 商品名を入力 -->
                        <div class="left_padding top_padding"> 2, 業者名:</div>
                        <div class="trader_name">{{ t_name }}</div>
                        <!-- 業者名を入力 -->
                    </div>
                    <div class="reason_area">
                        <!-- 必要理由を自動入力 -->
                        <div class="left_padding">3, 必要理由</div>
                        <div id="reason_text">{{ reason }}</div>
                        <!-- 必要理由を自動入力 -->
                    </div>
                    <div class="trader_reason_area">
                        <!-- 業者選定理由を入力 -->
                        <div class="left_padding"> 4, 業者選定理由</div>
                        <div id="trader_reason_area">{{ t_reason }}</div>
                        <!-- 業者選定理由を入力 -->
                    </div>
                    <div class="remarks">
                        <!-- 備考を自動入力 -->
                        <div class="left_padding"> 5, 備考</div>
                        <div id="remarks" class="form-group">{{ remarks }}
                        </div>
                        <!-- 備考を自動入力 -->
                    </div>

                    <!-- ボタン部分 -->
                    <div></div>
                    <div class="bottom_area">
                        <div class="approval">
                            <div class="position">主任</div>
                            <div class="position">部長</div>
                            <div class="position">常務取締役</div>
                            <div class="position">社長</div>
                            <div class="decision_1"></div>
                            <div class="decision_2"></div>
                            <div class="decision_3"></div>
                            <div class="decision_4"></div>
                        </div>
                        <!-- 作成時、作成者確認時には不要 -->
                        <div></div>
                        <div class="button">
                            <div class="docs_button">
                                <form action="{% url 'create:create' %}" method="GET">
                                    <button type="submit" id="back">戻る
                                        <input type="text" name="back" value="true" style="display: none">
                                    </button>
                                </form>
                            </div>

                            <div></div>
                            <div class="docs_button">
                                <form action="{% url 'create:check' %}" method="GET">
                                    <button type="submit" name="send" id="send">作成
                                    </button>
                                </form>
                            </div>
                            <div></div>
                            <div></div>
                            <div class="add_button"></div>
                        </div>
                    </div>
                    <div></div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
<script src="../../static/createRingisyo/js/bootstrap.min.js"></script>
<script src="../../static/createRingisyo/js/bootstrap.min.js.map"></script>
{% block addJS %}

{% endblock %}
</body>

</html>

createRingisyo/templates/createRingisyo/create.html
{% extends 'createRingisyo/base.html' %}
{% load static %}

<html lang="ja">
{% block title %}
    トップページ
{% endblock %}

<head>
    {% block addCSS %}
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.css">
        <link rel="stylesheet" href="{% static 'createRingisyo/css/create.css' %}">
    {% endblock %}

    <title>トップページ</title>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="../../static/createRingisyo/css/bootstrap.min.css">
    <link rel="stylesheet" href="../../static/createRingisyo/css/bootstrap.min.css.map">
    <link rel="stylesheet" href="../../static/createRingisyo/css/">

</head>

<body>
{% block body %}
    <div class="overflow">
        <div class="d-grid gap-2">
            <h2>稟議書作成画面</h2>
            <form id="form" action="{% url 'create:create' %}" method="GET" autocomplete="off">{% csrf_token %}
                <div class="wrapper">
                    <div class="wrapper-wrapper">
                        <div class="no_input no_input_wide" id="limit">承認期限<span>
                            <input type="text" id="datepicker" name="limit" required value="{{ limit }}">
                        </span>
                        </div>
                        <div class="no_input no_input_narrow">{{ user_former.department.department_name }}</div>
                    </div>
                    <div class="no_input no_input_narrow no_input_narrow_name">
                        {{ user_former.last_name }}{{ user_former.first_name }}</div>
                </div>
                <div class="no_wrapper"><input type="text" name="title" class="input_narrow" id="title"
                                               placeholder="件名(表題)" required value="{{ title }}" maxlength="32"></div>
                <div class="no_wrapper"><input type="text" name="product_name" class="input_narrow"
                                               placeholder="物品またはサービス名" required value="{{ p_name }}"></div>
                <div class="no_wrapper"><input type="text" name="trader_name" class="input_narrow" placeholder="業者名"
                                               required value="{{ t_name }}">
                </div>
                <div class="wrapper">
                    <div class="wrapper-wrapper">
                        <input type="text" id="quantity" name="quantity" class="input_short pay_piece" placeholder="数量"
                               required
                               value="{{ quantity }}">
                        <input type="text" id="unit_price" name="unit_price" class="input_short pay_piece"
                               placeholder="単価"
                               required
                               value="{{ unit_price }}">
                    </div>
                    <div class="no_input no_input_wide no_input_narrow_pay_all" id="payAll">支払総額</div>
                </div>
                <div class="no_wrapper"><input type="text" name="reason" class="input_wide" placeholder="必要理由" required
                                               value="{{ reason }}">
                </div>
                <div class="no_wrapper"><input type="text" name="trader_reason" class="input_wide" placeholder="業者選定理由"
                                               required value="{{ t_reason }}">
                </div>
                <div class="no_wrapper"><input type="text" name="remarks" class="input_wide" placeholder="備考"
                                               value="{{ remarks }}"></div>

            </form>
            <div class="wrapper_button">
                <button type="submit" onclick="location.href='{{ request.META.HTTP_REFERER }}'" name="back"
                        class="btn btn-secondary back">戻る
                </button>
                <button type="submit" form="form" name="edit" class="btn btn-secondary send">作成</button>
            </div>
        </div>
    </div>

{% endblock %}

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
<script src="../../static/createRingisyo/js/bootstrap.min.js"></script>
<script src="../../static/createRingisyo/js/bootstrap.min.js.map"></script>
{% block addJS %}
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js"></script>
    <script src="https://rawgit.com/jquery/jquery-ui/master/ui/i18n/datepicker-ja.js"></script>
    <script src="{% static 'createRingisyo/js/user_add.js' %}"></script>
    <script>
        $(function () {
            {% if alert is not None or alert is not Null %}
                window.alert("{{ alert }}");
            {% endif %}
            setPayAll();

            $(".pay_piece").blur(function () {
                setPayAll();
            });

            $('.pay_piece').on('input', function (e) {
                let value = $(e.currentTarget).val();
                value = value
                    .replace(/[０-９]/g, function (s) {
                        return String.fromCharCode(s.charCodeAt(0) - 65248);
                    })
                    .replace(/[^0-9]/g, '');
                $(e.currentTarget).val(value);
            });

            function setPayAll() {
                let quantity;
                let unit_price;
                let get_quantity = $("#quantity").val();
                let get_unit_price = $("#unit_price").val();

                if (get_quantity === null || get_unit_price === null) {
                    return;
                }
                if (get_quantity === "一式") {
                    quantity = 1;
                } else {
                    quantity = parseInt(get_quantity, 10);
                    if (isNaN(quantity)) {
                        quantity = 0;
                    }
                }
                if (typeof get_unit_price == "string") {
                    unit_price = parseInt(get_unit_price, 10);
                    if (isNaN(unit_price)) {
                        unit_price = 0;
                    }
                } else if (typeof get_unit_price == "number") {
                    unit_price = get_unit_price;
                }
                console.log(quantity);

                $("#payAll").text(quantity * unit_price );
            }
        })
    </script>
{% endblock %}
</body>

</html>